apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8000