apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: ghcr.io/YOUR_USERNAME/simple-python-ci-cd:IMAGE_TAG
          ports:
            - containerPort: 8000