apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: ghcr.io/haarish1999/onedata_simple_ci_cd:IMAGE_TAG
          ports:
            - containerPort: 8000